



------------------------------------------ CREACION DE TABLAAAAS ---------------------------------------------------------------

-- TABLA COMBOS ----------------------------------------------------------------------------------------------------------------
CREATE TABLE combos
 (combo_id number GENERATED by default on null as IDENTITY,
  nombre varchar2(50) NOT NULL,
  tipocombo_id number(10),
  detalle_combo_id number(10),
  precio_id number(10) NOT NULL,
  CONSTRAINT combos_pk PRIMARY KEY (combo_id) 
  );
  
    ALTER TABLE COMBOS ADD CONSTRAINT fk_tipocombo
    FOREIGN KEY (tipocombo_id) REFERENCES tipocombo(tipocombo_id);

   -- crar detalle_combo_ primero
        ALTER TABLE COMBOS ADD CONSTRAINT fk_detalle_combo
        FOREIGN KEY (detalle_combo_id) REFERENCES detalle_combo(detalle_combo_id);

        ALTER TABLE COMBOS ADD CONSTRAINT fk_precios_combo
        FOREIGN KEY (precio_id) REFERENCES precios(precio_id);

-- TABLA TIPO_COMBOS -----------------------------------------------------------------------------------------------------------
CREATE TABLE tipocombo
( tipocombo_id number GENERATED by default on null as IDENTITY,
  nombretipo varchar2(50) NOT NULL,
  CONSTRAINT tipocombo_id PRIMARY KEY (tipocombo_id)
);

-- TABLA BEBESTIBLES -----------------------------------------------------------------------------------------------------------
CREATE TABLE bebestibles
( bebestible_id number GENERATED by default on null as IDENTITY,
  nombre varchar2(50) NOT NULL,
  precio_id number(10),
  CONSTRAINT bebestible_id PRIMARY KEY (bebestible_id)
);
        ALTER TABLE bebestibles ADD CONSTRAINT fk_bebestibles_precios
        FOREIGN KEY (precio_id) REFERENCES precios(precio_id);

-- TABLA ALIMENTOS -------------------------------------------------------------------------------------------------------------
CREATE TABLE alimentos
( alimento_id number GENERATED by default on null as IDENTITY,
  nombre varchar2(50) NOT NULL,
  precio_id number(10),
  CONSTRAINT alimento_id PRIMARY KEY (alimento_id)
);
        ALTER TABLE alimentos ADD CONSTRAINT alimentos_precios
        FOREIGN KEY (precio_id) REFERENCES precios(precio_id);

-- TABLA ACOMPANANIMENTOS ------------------------------------------------------------------------------------------------------
CREATE TABLE acompanamientos
( acompanamiento_id number GENERATED by default on null as IDENTITY,
  nombre varchar2(50) NOT NULL,
  precio_id number(10),
  CONSTRAINT acompanamiento_id PRIMARY KEY (acompanamiento_id)
);
        ALTER TABLE acompanamientos ADD CONSTRAINT acompanamientos_precios
        FOREIGN KEY (precio_id) REFERENCES precios(precio_id);

-- TABLA PRECIOS ---------------------------------------------------------------------------------------------------------------
CREATE TABLE precios
 ( precio_id number GENERATED by default on null as IDENTITY,
   precio number(10) NOT NULL,
  CONSTRAINT precio_id PRIMARY KEY (precio_id)
);
       
-- TABLA DETALLE_COMBO ---------------------------------------------------------------------------------------------------------
CREATE TABLE detalle_combo
 (detalle_combo_id number GENERATED by default on null as IDENTITY,
  bebestible_id number(10) ,
  cant_bebestibles number(5),
  alimento_id number(10), 
  cant_alimento number(5),
  acompanamiento_id_1 number(10),
  cant_acompanamiento_1 number(5),
  acompanamiento_id_2 number(10),
  cant_acompanamiento_2 number(5),
  CONSTRAINT detalle_combo_id PRIMARY KEY (detalle_combo_id)
);

        ALTER TABLE detalle_combo ADD CONSTRAINT fk_detalle_combo_bebestible
        FOREIGN KEY (bebestible_id) REFERENCES bebestibles(bebestible_id);
        
        ALTER TABLE detalle_combo ADD CONSTRAINT fk_detalle_combo_alimento
        FOREIGN KEY (alimento_id) REFERENCES alimentos(alimento_id);
         
        ALTER TABLE detalle_combo ADD CONSTRAINT fk_detalle_combo_Acompanamiento_1
        FOREIGN KEY (acompanamiento_id_1) REFERENCES acompanamientos(acompanamiento_id);
        
        ALTER TABLE detalle_combo ADD CONSTRAINT fk_detalle_combo_Acompanamiento_2
        FOREIGN KEY (acompanamiento_id_2) REFERENCES acompanamientos(acompanamiento_id);
        
-- TABLA PEDIDOS ---------------------------------------------------------------------------------------------------------------       
CREATE TABLE pedido
( pedido_id number GENERATED by default on null as IDENTITY,
  alimento_id number(10),
  cant_alimento number(5),
  bebestible_id number(10),
  cant_bebestible number(5),
  acompanamiento_id_1 number(10),
  cant_acompanamiento_1 number(5),
  acompanamiento_id_2 number(10),
  cant_acompanamiento_2 number(5),
  combo_id number(10),
  cant_combo number(5),
  CONSTRAINT pedido_pk PRIMARY KEY (pedido_id) 
  );
  
        ALTER TABLE pedido ADD CONSTRAINT fk_pedido_bebestible
        FOREIGN KEY (bebestible_id) REFERENCES bebestibles(bebestible_id);
        
        ALTER TABLE pedido ADD CONSTRAINT fk_pedido_alimento
        FOREIGN KEY (alimento_id) REFERENCES alimentos(alimento_id);
        
        ALTER TABLE pedido ADD CONSTRAINT fk_pedido_acompanamiento_1
        FOREIGN KEY (acompanamiento_id_1) REFERENCES acompanamientos(acompanamiento_id);
        
        ALTER TABLE pedido ADD CONSTRAINT fk_pedido_acompanamiento_2
        FOREIGN KEY (acompanamiento_id_2) REFERENCES acompanamientos(acompanamiento_id);
        
        ALTER TABLE pedido ADD CONSTRAINT fk_pedido_combo
        FOREIGN KEY (combo_id) REFERENCES combos(combo_id);

-- TABLA FACTURA/BOLETA --------------------------------------------------------------------------------------------------------
CREATE TABLE factura
( factura_id number  GENERATED by default on null as IDENTITY,
  pedido_id number(10),
  precio number(10),
  tipo_pago varchar2(50),
  fecha_venta date
  );

 
        ALTER TABLE factura ADD CONSTRAINT fk_factura
        FOREIGN KEY (pedido_id) REFERENCES pedido(pedido_id);